import type { CareerDetail } from "../types";
export const psychologySocial: CareerDetail = {
  slug: "psychology-social", careerName: "Psychology / Social Impact", title: "Psychologist & Social Impact Leader", tagline: "Understand human behavior, support mental health, and drive meaningful change in communities.", category: "Social Sciences & Impact", icon: "Heart", primaryTraits: ["SO", "SC"], relatedSlugs: ["medicine-healthcare", "law-policy", "marketing-media"],
  snapshot: [
    { label: "What You Do", value: "Study human behavior, provide counseling, design interventions, conduct research, and drive social change programs.", icon: "Users" },
    { label: "Entry-Level Roles", value: "Counselor Intern, Research Assistant, Social Worker, Community Organizer, NGO Program Associate", icon: "Briefcase" },
    { label: "Industries", value: "Healthcare, education, NGOs, government, corporate (I/O psychology), research, community development", icon: "Building2" },
    { label: "Work Environment", value: "Clinics, schools, community centers, research labs, corporate offices — people-focused and emotionally engaged", icon: "Monitor" },
    { label: "Difficulty to Enter", value: "Moderate — requires empathy and academic foundation. Advanced roles need MA/MSW/PhD.", icon: "Signal" },
    { label: "Growth Potential", value: "Growing — mental health awareness is increasing rapidly. Organizational psychologists are in high demand.", icon: "TrendingUp" },
  ],
  skills: [
    { id: "psych-foundations", name: "Psychology Fundamentals", category: "Foundation", relevantTraits: ["SC", "SO"], whyItMatters: "Understanding how people think, feel, and behave is the foundation of all psychology and social impact work.", whatToKnow: "Developmental psychology, cognitive psychology, social psychology, abnormal psychology, personality theories.", recommendedLevel: "Explain major psychological theories and their applications" },
    { id: "counseling", name: "Counseling & Active Listening", category: "Core", relevantTraits: ["SO"], whyItMatters: "The ability to listen deeply, empathize, and guide people through challenges is central to psychological practice.", whatToKnow: "Active listening, empathy techniques, rapport building, ethical boundaries, crisis intervention basics.", recommendedLevel: "Conduct a supportive conversation using active listening techniques" },
    { id: "research-psych", name: "Research Methods & Assessment", category: "Core", relevantTraits: ["SC", "AN"], whyItMatters: "Psychology is a science. Conducting rigorous research and using validated assessment tools is essential.", whatToKnow: "Research design, qualitative & quantitative methods, surveys, statistical analysis, psychological testing.", recommendedLevel: "Design and conduct a simple psychology study" },
    { id: "community-dev", name: "Community Development & Social Work", category: "Domain", relevantTraits: ["SO", "LE"], whyItMatters: "Creating lasting social change requires understanding communities, designing programs, and mobilizing resources.", whatToKnow: "Needs assessment, program design, stakeholder engagement, monitoring & evaluation, grant writing.", recommendedLevel: "Design a community intervention program" },
    { id: "behavioral-insights", name: "Behavioral Insights & I/O Psychology", category: "Advanced", relevantTraits: ["AN", "BU"], whyItMatters: "Applying psychology to organizations and policy design is a growing field with high impact and compensation.", whatToKnow: "Organizational behavior, nudge theory, behavioral economics, workplace culture, talent management.", recommendedLevel: "Apply behavioral insights to improve an organizational process" },
  ],
  roadmap: [
    { id: "psy-phase-1", phase: 1, title: "Psychology Foundations", description: "Build a strong understanding of human behavior and psychological principles.", estimatedDuration: "3–4 weeks", skills: ["Psychology Fundamentals"], learn: ["Major psychology schools of thought", "Developmental psychology", "Cognitive processes", "Social psychology basics", "Ethics in psychology"], practice: ["Read and summarize 5 psychology research papers", "Observe and document human behavior patterns"], build: "A presentation on a psychology topic that interests you", resources: [
      { name: "Crash Course Psychology (YouTube)", type: "video", difficulty: "beginner", estimatedTime: "8 hours", url: "https://www.youtube.com/playlist?list=PL8dPuuaLjXtOPRKzVLY0jJY-uHOH9KVU6" },
      { name: "Introduction to Psychology (MIT OCW)", type: "course", difficulty: "beginner", estimatedTime: "Semester", url: "https://ocw.mit.edu/courses/9-00sc-introduction-to-psychology-fall-2011/" },
      { name: "Thinking, Fast and Slow (book)", type: "book", difficulty: "intermediate", estimatedTime: "3 weeks", url: "https://us.macmillan.com/books/9780374533557/thinkingfastandslow" },
    ]},
    { id: "psy-phase-2", phase: 2, title: "Counseling & Communication", description: "Develop interpersonal skills and learn the basics of psychological counseling.", estimatedDuration: "3–4 weeks", skills: ["Counseling & Active Listening"], learn: ["Active listening techniques", "Empathy and rapport", "Non-verbal communication", "Ethical boundaries", "Basic crisis support"], practice: ["Practice active listening in 10 conversations", "Volunteer at a helpline or support group"], build: "A reflective journal documenting your counseling skill development", resources: [
      { name: "iCall (TISS) — Counseling Resources", type: "documentation", difficulty: "beginner", estimatedTime: "Ongoing", url: "https://icallhelpline.org/" },
      { name: "The Gift of Therapy (book)", type: "book", difficulty: "beginner", estimatedTime: "1 week", url: "https://www.harpercollins.com/products/the-gift-of-therapy-irvin-yalom" },
    ]},
    { id: "psy-phase-3", phase: 3, title: "Research & Community Impact", description: "Learn research methods and explore social impact through community engagement.", estimatedDuration: "4–6 weeks", skills: ["Research Methods & Assessment", "Community Development & Social Work"], learn: ["Research design basics", "Survey creation", "Data analysis for social sciences", "Community needs assessment", "Program design"], practice: ["Design and conduct a small survey (50+ respondents)", "Volunteer with an NGO or community organization"], build: "A community needs assessment report with recommendations", resources: [
      { name: "Coursera — Research Methods in Social Science", type: "course", difficulty: "intermediate", estimatedTime: "6 weeks", url: "https://www.coursera.org/learn/social-science-research" },
      { name: "iVolunteer — Find Volunteering Opportunities", type: "documentation", difficulty: "beginner", estimatedTime: "Ongoing", url: "https://www.ivolunteer.in/" },
    ]},
  ],
  projects: [
    { title: "Psychology Awareness Campaign", difficulty: "beginner", skills: ["Communication", "Psychology Fundamentals", "Organization"], description: "Design and run a mental health or psychology awareness campaign at your school or in your community.", features: ["Research-backed content", "Engaging presentation or workshop", "Anonymous Q&A session", "Resource handouts", "Impact documentation"], portfolioValue: "Shows initiative, communication skills, and commitment to mental health — valued by psychology programs." },
    { title: "Behavioral Observation Study", difficulty: "intermediate", skills: ["Research Methods", "Data Analysis", "Writing"], description: "Design and conduct a structured behavioral observation study — analyzing patterns in human behavior in a specific context.", features: ["Clear research question", "Systematic observation protocol", "Data collection", "Statistical analysis", "Written report with findings"], portfolioValue: "Demonstrates research aptitude and systematic thinking — exactly what graduate programs look for." },
    { title: "Community Intervention Program", difficulty: "advanced", skills: ["Community Development", "Research", "Leadership"], description: "Design, implement, and evaluate a community intervention program addressing a real social issue.", features: ["Needs assessment", "Program design with theory of change", "Implementation with community", "Pre/post measurement", "Impact evaluation report", "Presentation to stakeholders"], portfolioValue: "A genuine social impact project that demonstrates leadership, empathy, and research skills — powerful for any social sciences application." },
  ],
  progression: [
    { title: "Psychology Student / Volunteer", yearsRange: "During BA/BSc", responsibilities: ["Study psychology", "Volunteer at organizations", "Assist in research", "Gain practical exposure"], skills: ["Psychology knowledge", "Empathy", "Communication", "Research basics"], deltaFromPrevious: "Foundation years — building knowledge and gaining exposure to the field." },
    { title: "Counselor / Social Worker (Entry)", yearsRange: "0–3 years post-MA/MSW", responsibilities: ["Provide counseling", "Case management", "Community outreach", "Documentation"], skills: ["Counseling skills", "Assessment", "Ethical practice", "Cultural sensitivity"], deltaFromPrevious: "Begin practicing with real clients under supervision." },
    { title: "Senior Counselor / Program Manager", yearsRange: "3–7 years", responsibilities: ["Lead programs", "Supervise junior staff", "Design interventions", "Stakeholder management"], skills: ["Clinical expertise", "Program management", "Leadership", "Grant writing"], deltaFromPrevious: "Transition from direct service to program-level impact." },
    { title: "Clinical Psychologist / Director", yearsRange: "7–12 years", responsibilities: ["Independent practice", "Organizational consulting", "Policy advocacy", "Training and supervision"], skills: ["Advanced clinical skills", "Organizational leadership", "Research", "Public speaking"], deltaFromPrevious: "Become an expert practitioner or organizational leader." },
    { title: "Thought Leader / Professor", yearsRange: "12+ years", responsibilities: ["Shape the field", "Publish research", "Advise policy", "Train the next generation"], skills: ["Research leadership", "Academic writing", "Policy influence", "Mentorship"], deltaFromPrevious: "Influence the field of psychology and social impact at a systemic level." },
  ],
  preparation: [
    { id: "psy-prep-1", category: "Volunteering", task: "Volunteer at a mental health or social organization", details: "Gain real experience with people and communities. Even a few hours per week builds invaluable perspective." },
    { id: "psy-prep-2", category: "Reading", task: "Read 3 psychology books", details: "'Thinking, Fast and Slow', 'Man's Search for Meaning', 'The Boy Who Was Raised as a Dog'." },
    { id: "psy-prep-3", category: "Education", task: "Choose Humanities or relevant subjects", details: "Psychology, sociology, and political science in Class 11-12 provide excellent preparation." },
    { id: "psy-prep-4", category: "Skills", task: "Practice active listening", details: "In every conversation, focus on truly listening before responding. This is the most important counseling skill." },
    { id: "psy-prep-5", category: "Exposure", task: "Attend psychology workshops or webinars", details: "Many universities and organizations offer free workshops on mental health and psychology topics." },
  ],
};
