import type { CareerDetail } from "../types";
export const scientificResearch: CareerDetail = {
  slug: "scientific-research", careerName: "Scientific Research", title: "Research Scientist", tagline: "Push the boundaries of human knowledge through experimentation, observation, and analysis.", category: "Science & Research", icon: "FlaskConical", primaryTraits: ["SC", "AN"], relatedSlugs: ["ai-ml-data-science", "medicine-healthcare", "engineering"],
  snapshot: [
    { label: "What You Do", value: "Design experiments, collect data, test hypotheses, publish findings, and advance understanding in your field of science.", icon: "Microscope" },
    { label: "Entry-Level Roles", value: "Research Assistant, Lab Technician, Junior Scientist, Graduate Researcher, Data Analyst", icon: "Briefcase" },
    { label: "Industries", value: "Universities, government labs, pharma, biotech, tech companies, space agencies, environmental orgs", icon: "Building2" },
    { label: "Work Environment", value: "Laboratories, field stations, universities, clean rooms — deep focus work with periodic collaboration", icon: "Monitor" },
    { label: "Difficulty to Enter", value: "High — typically requires advanced degrees (MSc/PhD). Long training period but deeply rewarding.", icon: "Signal" },
    { label: "Growth Potential", value: "Moderate salary but high impact. Leading researchers shape entire fields and win prestigious recognition.", icon: "TrendingUp" },
  ],
  skills: [
    { id: "scientific-method", name: "Scientific Method & Experimental Design", category: "Foundation", relevantTraits: ["SC", "AN"], whyItMatters: "The ability to formulate hypotheses, design controlled experiments, and draw valid conclusions is the foundation of all research.", whatToKnow: "Hypothesis formulation, variable control, experimental design, reproducibility, peer review process.", recommendedLevel: "Design and execute a simple experiment independently" },
    { id: "data-analysis-sci", name: "Data Analysis & Statistics", category: "Core", relevantTraits: ["AN", "SC"], whyItMatters: "Research generates data that must be analyzed rigorously. Statistical analysis determines whether findings are meaningful.", whatToKnow: "Descriptive and inferential statistics, hypothesis testing, p-values, regression, R or Python for analysis.", recommendedLevel: "Perform statistical analysis on experimental data" },
    { id: "academic-writing", name: "Academic Writing & Communication", category: "Core", relevantTraits: ["AN"], whyItMatters: "Research is only valuable when communicated. Writing papers, giving talks, and explaining findings is essential.", whatToKnow: "Research paper structure (IMRaD), citation practices, literature review, conference presentations, grant writing.", recommendedLevel: "Write a structured research report or poster" },
    { id: "lab-skills", name: "Laboratory Skills", category: "Domain", relevantTraits: ["SC", "TE"], whyItMatters: "Hands-on lab skills are essential for experimental sciences — from pipetting to operating specialized equipment.", whatToKnow: "Lab safety, measurement techniques, instrument calibration, sample preparation, record keeping.", recommendedLevel: "Work safely and accurately in a science laboratory" },
    { id: "computational-sci", name: "Computational Tools", category: "Tools", relevantTraits: ["TE", "AN"], whyItMatters: "Modern research relies heavily on computation — from data analysis scripts to simulation software.", whatToKnow: "Python/R for analysis, MATLAB, LaTeX for papers, reference managers, version control for code.", recommendedLevel: "Use computational tools for data analysis and visualization" },
  ],
  roadmap: [
    { id: "sci-phase-1", phase: 1, title: "Science Foundations & Curiosity", description: "Build deep understanding in your chosen science and develop the curiosity that drives all research.", estimatedDuration: "Ongoing (Class 11-12)", skills: ["Scientific Method & Experimental Design"], learn: ["Deep study of your chosen science", "Scientific method", "Lab safety and techniques", "Science history and breakthroughs", "Critical thinking"], practice: ["Participate in Science Olympiad or NTSE", "Complete 5 science experiments at home"], build: "A science fair project with hypothesis, experiment, data, and conclusions", resources: [
      { name: "MIT OCW — Introductory Sciences", type: "course", difficulty: "beginner", estimatedTime: "Semester", url: "https://ocw.mit.edu/" },
      { name: "Veritasium / Kurzgesagt (YouTube)", type: "video", difficulty: "beginner", estimatedTime: "Ongoing", url: "https://www.youtube.com/@veritasium" },
      { name: "Science Olympiad Resources", type: "practice", difficulty: "intermediate", estimatedTime: "Ongoing", url: "https://www.scienceolympiad.org/" },
    ]},
    { id: "sci-phase-2", phase: 2, title: "Data Analysis & Computation", description: "Learn to analyze data scientifically and use computational tools for research.", estimatedDuration: "3–4 weeks", skills: ["Data Analysis & Statistics", "Computational Tools"], learn: ["Statistics fundamentals", "Python/R for data analysis", "Data visualization", "LaTeX for scientific writing", "Version control basics"], practice: ["Analyze 3 public scientific datasets", "Create publication-quality plots"], build: "A data analysis project on a publicly available research dataset", resources: [
      { name: "Khan Academy — Statistics", type: "course", difficulty: "beginner", estimatedTime: "4 weeks", url: "https://www.khanacademy.org/math/statistics-probability" },
      { name: "Python for Scientists (Real Python)", type: "course", difficulty: "beginner", estimatedTime: "2 weeks", url: "https://realpython.com/" },
      { name: "Overleaf LaTeX Tutorial", type: "documentation", difficulty: "beginner", estimatedTime: "1 week", url: "https://www.overleaf.com/learn" },
    ]},
    { id: "sci-phase-3", phase: 3, title: "Research Practice & Communication", description: "Practice the full research cycle — from question to publication.", estimatedDuration: "4–8 weeks", skills: ["Academic Writing & Communication", "Laboratory Skills"], learn: ["Literature review techniques", "Research paper writing", "Poster and presentation design", "Peer review process", "Research ethics"], practice: ["Write a 5-page research report", "Present findings at a school science event"], build: "A complete research project: question → literature review → experiment → analysis → report", resources: [
      { name: "How to Read a Paper (Keshav)", type: "documentation", difficulty: "beginner", estimatedTime: "1 hour", url: "https://web.stanford.edu/class/ee384m/Handouts/HowtoReadPaper.pdf" },
      { name: "Google Scholar", type: "documentation", difficulty: "beginner", estimatedTime: "Ongoing", url: "https://scholar.google.com/" },
    ]},
  ],
  projects: [
    { title: "Home Science Experiment Series", difficulty: "beginner", skills: ["Scientific Method", "Data Collection", "Analysis"], description: "Design and conduct 5 experiments at home using everyday materials, documenting each with proper scientific method.", features: ["Clear hypothesis for each", "Controlled variables", "Data tables and graphs", "Conclusions and error analysis", "Photo/video documentation"], portfolioValue: "Demonstrates scientific thinking and initiative — exactly what research programs look for." },
    { title: "Data-Driven Environmental Study", difficulty: "intermediate", skills: ["Data Analysis", "Statistics", "Communication"], description: "Collect environmental data in your local area (air quality, water quality, biodiversity) and produce a research report.", features: ["Data collection methodology", "Statistical analysis", "Visualization", "Comparison with published data", "Recommendations"], portfolioValue: "Shows ability to conduct independent research with real-world relevance and rigorous methodology." },
    { title: "Computational Research Project", difficulty: "advanced", skills: ["Computation", "Statistics", "Domain Knowledge"], description: "Use computational methods to investigate a scientific question — simulation, data mining, or modeling.", features: ["Literature-informed hypothesis", "Computational methodology", "Results with statistical significance", "Publication-quality figures", "Full research paper"], portfolioValue: "A genuine research contribution that can be presented at science fairs, Olympiads, or included in college applications." },
  ],
  progression: [
    { title: "Undergraduate Researcher", yearsRange: "During BSc/BTech", responsibilities: ["Assist in lab work", "Learn techniques", "Read papers", "Present at department seminars"], skills: ["Lab techniques", "Data analysis", "Scientific reading"], deltaFromPrevious: "First exposure to real research — learning the workflow." },
    { title: "Graduate Researcher (MSc/PhD)", yearsRange: "2–6 years", responsibilities: ["Conduct independent research", "Publish papers", "Present at conferences", "Teach undergraduates"], skills: ["Research design", "Advanced analysis", "Academic writing", "Teaching"], deltaFromPrevious: "Transition to independent research with original contributions." },
    { title: "Postdoctoral Researcher", yearsRange: "2–4 years post-PhD", responsibilities: ["Lead research projects", "Publish in top journals", "Build research network", "Apply for grants"], skills: ["Research leadership", "Grant writing", "Collaboration", "Mentoring"], deltaFromPrevious: "Deepen expertise and build the reputation needed for permanent positions." },
    { title: "Assistant / Associate Professor", yearsRange: "6–12 years total", responsibilities: ["Run your own lab", "Supervise students", "Teach courses", "Secure funding"], skills: ["Lab management", "Mentorship", "Teaching", "Fund raising"], deltaFromPrevious: "Lead a research group and shape the next generation of scientists." },
    { title: "Full Professor / Research Director", yearsRange: "15+ years", responsibilities: ["Set research direction", "Lead large programs", "Advise institutions", "Shape your field"], skills: ["Vision", "Scientific leadership", "Policy influence", "Legacy building"], deltaFromPrevious: "Become a leader in your field with impact that spans decades." },
  ],
  preparation: [
    { id: "sci-prep-1", category: "Education", task: "Choose Science in Class 11", details: "Select subjects aligned with your interest (PCM for physical sciences, PCB for life sciences)." },
    { id: "sci-prep-2", category: "Competition", task: "Participate in Science Olympiad / NTSE", details: "These competitions develop scientific thinking and are valued by research programs." },
    { id: "sci-prep-3", category: "Reading", task: "Read popular science books", details: "Try 'A Short History of Nearly Everything', 'The Gene', or 'Cosmos'. Build genuine curiosity." },
    { id: "sci-prep-4", category: "Projects", task: "Complete a science fair project", details: "Design an original experiment with proper methodology. Document everything." },
    { id: "sci-prep-5", category: "Programs", task: "Apply to IISER/IISc/research programs", details: "These institutions focus on research-oriented education. Look into KVPY and INSPIRE scholarships." },
  ],
};
