import type { CareerDetail } from "../types";

export const softwareDevelopment: CareerDetail = {
  slug: "software-development",
  careerName: "Software Development",
  title: "Software Development",
  tagline: "Build applications, websites, and digital tools that power everyday life.",
  category: "Technology",
  icon: "Cpu",
  primaryTraits: ["TE", "AN"],
  relatedSlugs: ["ai-ml-data-science", "engineering", "design-creative"],

  snapshot: [
    { label: "What You Do", value: "Design, build, and maintain software applications — from mobile apps and websites to backend systems and APIs.", icon: "Code" },
    { label: "Entry-Level Roles", value: "Junior Developer, Frontend Developer, Backend Developer, Full-Stack Intern, QA Engineer", icon: "Briefcase" },
    { label: "Industries", value: "Tech companies, startups, finance, healthcare, e-commerce, education, gaming, government", icon: "Building2" },
    { label: "Work Environment", value: "Office or remote, collaborative teams, agile sprints, code reviews, flexible hours common", icon: "Monitor" },
    { label: "Difficulty to Enter", value: "Moderate — strong portfolio and problem-solving skills matter more than formal degrees", icon: "Signal" },
    { label: "Growth Potential", value: "Very high — one of the fastest-growing career fields globally with strong salary growth", icon: "TrendingUp" },
  ],

  skills: [
    {
      id: "programming",
      name: "Programming Fundamentals",
      category: "Foundation",
      relevantTraits: ["TE", "AN"],
      whyItMatters: "Programming is the core skill of software development. Understanding variables, loops, functions, and data types lets you translate ideas into working code.",
      whatToKnow: "Master at least one language (Python or JavaScript recommended). Understand control flow, functions, error handling, and basic OOP.",
      recommendedLevel: "Confident writing 100+ line programs independently",
    },
    {
      id: "dsa",
      name: "Data Structures & Algorithms",
      category: "Foundation",
      relevantTraits: ["AN", "SC"],
      whyItMatters: "DSA teaches you to solve problems efficiently. It's the basis for technical interviews and writing performant code.",
      whatToKnow: "Arrays, strings, linked lists, stacks, queues, trees, hash maps, basic sorting and searching algorithms, Big-O notation.",
      recommendedLevel: "Solve easy–medium problems on LeetCode / HackerRank",
    },
    {
      id: "git",
      name: "Git & Version Control",
      category: "Tools",
      relevantTraits: ["TE"],
      whyItMatters: "Every professional development team uses Git. It tracks changes, enables collaboration, and is essential for open-source contributions.",
      whatToKnow: "git init, add, commit, push, pull, branch, merge, pull requests, resolving conflicts, GitHub workflow.",
      recommendedLevel: "Comfortable managing branches and pull requests",
    },
    {
      id: "databases",
      name: "Databases",
      category: "Backend",
      relevantTraits: ["TE", "AN"],
      whyItMatters: "Almost every application stores data. Understanding databases lets you design data models and write efficient queries.",
      whatToKnow: "SQL basics (SELECT, JOIN, INSERT, UPDATE), relational vs NoSQL, database design, indexing, ORMs.",
      recommendedLevel: "Design a schema and write CRUD queries confidently",
    },
    {
      id: "apis",
      name: "APIs & HTTP",
      category: "Backend",
      relevantTraits: ["TE"],
      whyItMatters: "APIs are how different software systems communicate. Understanding REST APIs is essential for full-stack development.",
      whatToKnow: "HTTP methods (GET, POST, PUT, DELETE), status codes, JSON, REST principles, authentication headers, API testing.",
      recommendedLevel: "Build and consume REST APIs independently",
    },
    {
      id: "framework",
      name: "Backend Framework",
      category: "Backend",
      relevantTraits: ["TE", "AN"],
      whyItMatters: "Frameworks provide structure for building web applications quickly. They handle routing, middleware, and common patterns.",
      whatToKnow: "Choose one: Express.js (Node), Django/FastAPI (Python), or Spring Boot (Java). Learn routing, middleware, templating, and deployment.",
      recommendedLevel: "Build a complete CRUD application with authentication",
    },
    {
      id: "auth",
      name: "Authentication & Security",
      category: "Security",
      relevantTraits: ["TE", "AN"],
      whyItMatters: "Protecting user data is critical. Understanding authentication and basic security prevents common vulnerabilities.",
      whatToKnow: "Password hashing, JWTs, OAuth2, session management, HTTPS, CORS, input validation, OWASP Top 10.",
      recommendedLevel: "Implement secure login/signup in a project",
    },
    {
      id: "deployment",
      name: "Deployment & DevOps",
      category: "Operations",
      relevantTraits: ["TE", "EX"],
      whyItMatters: "Code is only valuable when it's running in production. Deployment skills let you ship real software to real users.",
      whatToKnow: "Cloud basics (AWS/Vercel/Railway), Docker fundamentals, CI/CD pipelines, environment variables, monitoring.",
      recommendedLevel: "Deploy a full-stack app to a cloud platform",
    },
    {
      id: "system-design",
      name: "System Design",
      category: "Advanced",
      relevantTraits: ["AN", "TE", "SC"],
      whyItMatters: "As you grow, you'll need to design systems that scale. System design is crucial for senior roles and interviews.",
      whatToKnow: "Load balancing, caching, database sharding, microservices vs monoliths, message queues, CDNs.",
      recommendedLevel: "Discuss trade-offs in system architecture",
    },
  ],

  roadmap: [
    {
      id: "phase-1",
      phase: 1,
      title: "Programming Foundations",
      description: "Learn a programming language and build comfort with writing code from scratch.",
      estimatedDuration: "2–3 weeks",
      skills: ["Programming Fundamentals"],
      learn: ["Variables & data types", "Functions & scope", "Control flow (if/else, loops)", "Object-Oriented Programming basics", "File I/O and error handling"],
      practice: ["Complete 20 small coding challenges on HackerRank or Codewars"],
      build: "A CLI-based to-do list or calculator app",
      resources: [
        { name: "CS50 Introduction to Computer Science", type: "course", difficulty: "beginner", estimatedTime: "12 weeks (self-paced)", url: "https://cs50.harvard.edu/" },
        { name: "freeCodeCamp JavaScript Algorithms", type: "course", difficulty: "beginner", estimatedTime: "300 hours", url: "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/" },
        { name: "Python for Everybody", type: "course", difficulty: "beginner", estimatedTime: "8 weeks", url: "https://www.py4e.com/" },
      ],
    },
    {
      id: "phase-2",
      phase: 2,
      title: "Data Structures & Algorithms",
      description: "Build problem-solving skills that are essential for technical interviews and efficient code.",
      estimatedDuration: "4–6 weeks",
      skills: ["Data Structures & Algorithms"],
      learn: ["Arrays & Strings", "Linked Lists", "Stacks & Queues", "Trees & Graphs", "Hash Maps", "Sorting & Searching", "Big-O notation"],
      practice: ["Solve 50–75 problems across easy and medium difficulty"],
      build: "Implement a custom data structure library",
      resources: [
        { name: "NeetCode Roadmap", type: "practice", difficulty: "beginner", estimatedTime: "Ongoing", url: "https://neetcode.io/roadmap" },
        { name: "Grokking Algorithms (book)", type: "book", difficulty: "beginner", estimatedTime: "2 weeks", url: "https://www.manning.com/books/grokking-algorithms" },
        { name: "LeetCode Easy Problems", type: "practice", difficulty: "beginner", estimatedTime: "Ongoing", url: "https://leetcode.com/problemset/all/?difficulty=EASY" },
      ],
    },
    {
      id: "phase-3",
      phase: 3,
      title: "Git, Web Basics & Databases",
      description: "Learn the tools and infrastructure that every developer uses daily.",
      estimatedDuration: "2–3 weeks",
      skills: ["Git & Version Control", "Databases"],
      learn: ["Git workflow (branch, commit, PR)", "HTML & CSS fundamentals", "SQL queries and joins", "Database design and normalization", "Introduction to NoSQL (MongoDB)"],
      practice: ["Create a GitHub profile with 3+ repositories", "Complete SQLBolt or SQLZoo exercises"],
      build: "A personal portfolio website with a contact form backed by a database",
      resources: [
        { name: "Git & GitHub for Beginners (freeCodeCamp)", type: "video", difficulty: "beginner", estimatedTime: "1 hour", url: "https://www.youtube.com/watch?v=RGOj5yH7evk" },
        { name: "SQLBolt Interactive SQL Tutorial", type: "practice", difficulty: "beginner", estimatedTime: "4 hours", url: "https://sqlbolt.com/" },
        { name: "MDN Web Docs — HTML & CSS", type: "documentation", difficulty: "beginner", estimatedTime: "1 week", url: "https://developer.mozilla.org/en-US/docs/Learn" },
      ],
    },
    {
      id: "phase-4",
      phase: 4,
      title: "Backend Development",
      description: "Build server-side applications with APIs, authentication, and real databases.",
      estimatedDuration: "4–6 weeks",
      skills: ["APIs & HTTP", "Backend Framework", "Authentication & Security"],
      learn: ["RESTful API design", "Request/response cycle", "Middleware and routing", "JWT authentication", "Input validation and error handling", "Database ORMs"],
      practice: ["Build 3 small API projects with increasing complexity"],
      build: "A full-featured REST API (e.g., blog platform or task manager) with auth",
      resources: [
        { name: "The Odin Project — Node.js Path", type: "course", difficulty: "intermediate", estimatedTime: "8 weeks", url: "https://www.theodinproject.com/paths/full-stack-javascript" },
        { name: "FastAPI Official Tutorial", type: "documentation", difficulty: "intermediate", estimatedTime: "2 weeks", url: "https://fastapi.tiangolo.com/tutorial/" },
        { name: "Postman API Testing", type: "practice", difficulty: "beginner", estimatedTime: "3 hours", url: "https://www.postman.com/resources/videos-tutorials/" },
      ],
    },
    {
      id: "phase-5",
      phase: 5,
      title: "Full-Stack Integration & Deployment",
      description: "Connect frontend and backend, deploy to the cloud, and build complete applications.",
      estimatedDuration: "3–4 weeks",
      skills: ["Deployment & DevOps"],
      learn: ["Frontend framework basics (React or Next.js)", "Connecting frontend to API", "Environment variables and config", "Docker basics", "CI/CD with GitHub Actions", "Cloud deployment (Vercel, Railway, or AWS)"],
      practice: ["Deploy 2 projects to production"],
      build: "A full-stack SaaS application deployed to the cloud",
      resources: [
        { name: "Next.js Official Learn Course", type: "course", difficulty: "intermediate", estimatedTime: "2 weeks", url: "https://nextjs.org/learn" },
        { name: "Docker Getting Started", type: "documentation", difficulty: "intermediate", estimatedTime: "1 week", url: "https://docs.docker.com/get-started/" },
        { name: "Vercel Deployment Guide", type: "documentation", difficulty: "beginner", estimatedTime: "1 hour", url: "https://vercel.com/docs" },
      ],
    },
    {
      id: "phase-6",
      phase: 6,
      title: "System Design & Career Prep",
      description: "Learn to think at scale, prepare for interviews, and build your professional brand.",
      estimatedDuration: "4–6 weeks",
      skills: ["System Design"],
      learn: ["Load balancing & caching", "Horizontal vs vertical scaling", "Database replication", "Microservices architecture", "Message queues", "Design patterns"],
      practice: ["Practice 10 system design problems", "Complete 100+ DSA problems total", "Mock interview sessions"],
      build: "A portfolio website showcasing all your projects with case studies",
      resources: [
        { name: "System Design Primer (GitHub)", type: "documentation", difficulty: "intermediate", estimatedTime: "Ongoing", url: "https://github.com/donnemartin/system-design-primer" },
        { name: "Designing Data-Intensive Applications (book)", type: "book", difficulty: "advanced", estimatedTime: "4 weeks", url: "https://dataintensive.net/" },
        { name: "Pramp — Free Mock Interviews", type: "practice", difficulty: "intermediate", estimatedTime: "Ongoing", url: "https://www.pramp.com/" },
      ],
    },
  ],

  projects: [
    {
      title: "CLI Task Manager",
      difficulty: "beginner",
      skills: ["Programming Fundamentals", "File I/O"],
      description: "A command-line to-do application where users can add, complete, delete, and list tasks. Data persists to a local file.",
      features: ["Add/remove tasks", "Mark tasks as complete", "Filter by status", "Save to and load from a JSON file", "Color-coded output"],
      portfolioValue: "Demonstrates programming fundamentals, file handling, and clean code structure — a solid first project.",
    },
    {
      title: "Full-Stack Blog Platform",
      difficulty: "intermediate",
      skills: ["APIs", "Databases", "Authentication", "Frontend"],
      description: "A blog platform with user accounts, post creation with markdown support, comments, and an admin dashboard.",
      features: ["User registration and login (JWT)", "Create/edit/delete posts with Markdown", "Comment system", "Admin panel for moderation", "Responsive design", "Search and pagination"],
      portfolioValue: "Shows full-stack competence: auth, CRUD, database design, and a polished UI. A classic project that interviewers recognize.",
    },
    {
      title: "Real-Time Collaboration Tool",
      difficulty: "advanced",
      skills: ["System Design", "WebSockets", "Databases", "Deployment"],
      description: "A collaborative workspace where multiple users can edit documents, manage tasks, or draw on a shared canvas in real time.",
      features: ["Real-time sync with WebSockets", "User presence indicators", "Conflict resolution", "Room/workspace management", "Persistent storage", "Deployment with Docker"],
      portfolioValue: "Demonstrates advanced skills: real-time systems, concurrency, scalable architecture. A standout portfolio piece for senior internships.",
    },
  ],

  progression: [
    {
      title: "Intern / Trainee",
      yearsRange: "0–1 year",
      responsibilities: ["Fix bugs and write small features", "Learn codebase and team practices", "Write tests for existing code", "Participate in code reviews"],
      skills: ["Programming fundamentals", "Git basics", "Communication"],
      deltaFromPrevious: "Entry point — learning the professional development workflow.",
    },
    {
      title: "Junior Developer",
      yearsRange: "1–2 years",
      responsibilities: ["Build features independently", "Write clean, tested code", "Collaborate with designers and PMs", "Debug and resolve production issues"],
      skills: ["Solid DSA", "Framework proficiency", "Database design", "API development"],
      deltaFromPrevious: "Shift from guided work to independent feature ownership.",
    },
    {
      title: "Mid-Level Developer",
      yearsRange: "2–4 years",
      responsibilities: ["Design and implement complex features", "Mentor junior developers", "Contribute to architecture decisions", "Optimize performance"],
      skills: ["System design basics", "Performance optimization", "Code review skills", "Cross-team collaboration"],
      deltaFromPrevious: "Begin influencing technical decisions and mentoring others.",
    },
    {
      title: "Senior Developer",
      yearsRange: "4–7 years",
      responsibilities: ["Lead technical projects end-to-end", "Define coding standards and best practices", "Drive architecture decisions", "Unblock team members"],
      skills: ["Advanced system design", "Technical leadership", "Estimation and planning", "Deep domain expertise"],
      deltaFromPrevious: "Transition from individual contribution to technical leadership.",
    },
    {
      title: "Staff / Principal Engineer",
      yearsRange: "7–12 years",
      responsibilities: ["Set technical direction for large systems", "Solve cross-team technical challenges", "Influence engineering culture", "Evaluate new technologies"],
      skills: ["Org-wide system design", "Strategic thinking", "Technical writing", "Cross-functional leadership"],
      deltaFromPrevious: "Impact expands from one team to the entire engineering organization.",
    },
    {
      title: "Engineering Manager / Architect",
      yearsRange: "8+ years",
      responsibilities: ["Manage engineering teams", "Drive hiring and team growth", "Set long-term technical strategy", "Bridge business and engineering"],
      skills: ["People management", "Strategic planning", "Budgeting", "Stakeholder communication"],
      deltaFromPrevious: "Choose the management track (people) or architect track (deep technical). Both shape the direction of engineering.",
    },
  ],

  preparation: [
    { id: "prep-1", category: "GitHub", task: "Build a strong GitHub profile", details: "Create a professional README, pin your best repositories, maintain consistent commit history." },
    { id: "prep-2", category: "Portfolio", task: "Complete 2 portfolio-quality projects", details: "Build at least one full-stack project and one that solves a real problem. Include README with screenshots." },
    { id: "prep-3", category: "DSA", task: "Practice 50+ DSA problems", details: "Focus on arrays, strings, hash maps, and trees. Track your progress on LeetCode or NeetCode." },
    { id: "prep-4", category: "Resume", task: "Create a technical resume", details: "One page. Lead with projects and skills. Quantify impact where possible. Use a clean template." },
    { id: "prep-5", category: "Portfolio", task: "Deploy a personal portfolio website", details: "Showcase your projects, skills, and a brief about section. Host on Vercel or Netlify." },
    { id: "prep-6", category: "Interview", task: "Practice mock interviews", details: "Use Pramp or practice with a friend. Focus on explaining your thought process clearly." },
    { id: "prep-7", category: "Networking", task: "Start building your professional network", details: "Create a LinkedIn profile. Follow developers you admire. Engage with dev communities on Twitter/Discord." },
    { id: "prep-8", category: "Internship", task: "Apply to your first internship", details: "Target startups and mid-size companies. Apply to at least 10 positions. Customize each application." },
  ],
};
