import type { CareerDetail } from "../types";

export const upscCivilServices: CareerDetail = {
  slug: "upsc-civil-services",
  careerName: "UPSC Civil Services",
  title: "Civil Services & Public Administration Leader",
  tagline: "Drive public governance, constitutional administration, district development, and law enforcement across India.",
  category: "Civil Services & Public Administration",
  icon: "Landmark",
  primaryTraits: ["LE", "SO", "AN"],
  relatedSlugs: ["state-public-service-commissions", "law-policy", "management-product"],
  snapshot: [
    {
      label: "What You Do",
      value: "Lead district administration, formulate public policy, coordinate inter-departmental development, maintain public order, and manage revenue systems.",
      icon: "Landmark",
    },
    {
      label: "Available Pathways",
      value: "All-India Services (IAS, IPS, IFoS) and Central Services (IFS, IRS, IAAS) representing apex constitutional governance.",
      icon: "Shield",
    },
    {
      label: "Entry Examination",
      value: "UPSC Civil Services Examination (CSE) — annual 3-stage recruitment (Preliminary, Main Written, and Personality Test).",
      icon: "FileText",
    },
    {
      label: "Official Eligibility",
      value: "Bachelor's degree in any discipline from a recognized university. Minimum age 21 years as of August 1st of the examination year.",
      icon: "GraduationCap",
    },
    {
      label: "Suitability vs Exam",
      value: "Career suitability measures aptitude for ethical public leadership; examination success demands high-discipline syllabus mastery.",
      icon: "Sparkles",
    },
    {
      label: "Impact & Growth",
      value: "Apex governance influence — progress from Sub-Divisional Magistrate (SDM) / Assistant SP to District Collector, State Secretary, or Cabinet Secretary.",
      icon: "TrendingUp",
    },
  ],
  skills: [
    {
      id: "constitutional-polity",
      name: "Indian Polity & Constitutional Governance",
      category: "Core",
      relevantTraits: ["AN", "LE"],
      whyItMatters: "Constitutional comprehension is the bedrock of public administration, federal relations, and executive authority in India.",
      whatToKnow: "Preamble, Fundamental Rights & Duties, DPSP, Union & State Executives, Judiciary, Federal Structure, and Statutory Commissions.",
      recommendedLevel: "Analyze constitutional articles and their direct application to executive policy decisions",
    },
    {
      id: "administrative-ethics",
      name: "Administrative Ethics & Public Integrity",
      category: "Core",
      relevantTraits: ["LE", "SO"],
      whyItMatters: "Civil servants exercise immense statutory authority and must maintain probity, transparency, empathy, and constitutional impartiality.",
      whatToKnow: "Foundational values of civil service, emotional intelligence, ethical dilemmas in governance, RTI mechanisms, and Citizen Charters.",
      recommendedLevel: "Evaluate complex administrative case studies balancing statutory law, welfare priorities, and public order",
    },
    {
      id: "grassroots-development",
      name: "Public Policy & Grassroots Development",
      category: "Core",
      relevantTraits: ["SO", "AN"],
      whyItMatters: "Officers oversee direct execution of social sector programs, rural development schemes, healthcare initiatives, and poverty alleviation.",
      whatToKnow: "Social sector policy frameworks, Panchayati Raj institutions, sustainable development goals (SDGs), and public expenditure tracking.",
      recommendedLevel: "Assess implementation bottlenecks and propose measurable solutions for welfare schemes",
    },
    {
      id: "analytical-writing",
      name: "Structured Analytical & Answer Writing",
      category: "Domain",
      relevantTraits: ["AN", "SC"],
      whyItMatters: "Mains evaluation and civil administration both demand concise, multi-dimensional, objective written communication.",
      whatToKnow: "Multi-stakeholder analysis, introduction-body-conclusion format, data substantiation from official reports, and neutral perspective.",
      recommendedLevel: "Draft a well-rounded 250-word policy analysis examining economic, legal, social, and administrative dimensions",
    },
    {
      id: "crisis-leadership",
      name: "Crisis Management & Administrative Leadership",
      category: "Domain",
      relevantTraits: ["LE", "SO"],
      whyItMatters: "Administrators and police officers must make time-sensitive decisions during natural disasters, communal tensions, or logistical emergencies.",
      whatToKnow: "Disaster management protocols, police-magistracy coordination, inter-departmental mobilization, and crowd communication.",
      recommendedLevel: "Develop a standard operating procedure for emergency disaster relief or peaceful dispute resolution",
    },
  ],
  roadmap: [
    {
      id: "upsc-phase-1",
      phase: 1,
      title: "Foundations of Indian Polity & Civic Governance",
      description: "Build rigorous understanding of constitutional democracy, institutional architecture, and core NCERT foundations.",
      estimatedDuration: "4–6 weeks",
      skills: ["Indian Polity & Constitutional Governance", "Administrative Ethics & Public Integrity"],
      learn: [
        "Constitutional philosophy: Preamble, Fundamental Rights, Directive Principles of State Policy, and Basic Structure doctrine",
        "Institutional organs: President, Parliament, Supreme Court, High Courts, and Governor functions",
        "Foundations of Indian economic development, agrarian systems, and post-independence history",
        "Daily current affairs synthesis connecting national news with General Studies syllabus topics",
      ],
      practice: [
        "Analyze 5 landmark Supreme Court constitutional judgments (e.g. Kesavananda Bharati, Maneka Gandhi, Puttaswamy)",
        "Summarize monthly policy briefs from official government sources like Press Information Bureau (PIB)",
      ],
      build: "A foundational governance dossier: constitutional summaries, institutional maps, and a 1-month current affairs policy notebook.",
      resources: [
        {
          name: "UPSC Official Examination Portal & Syllabus",
          type: "documentation",
          difficulty: "beginner",
          estimatedTime: "Ongoing",
          url: "https://upsc.gov.in/",
        },
        {
          name: "NCERT Textbooks Online (Class 6–12 Foundations)",
          type: "documentation",
          difficulty: "beginner",
          estimatedTime: "Ongoing",
          url: "https://ncert.nic.in/textbook.php",
        },
        {
          name: "Press Information Bureau (PIB) Government of India",
          type: "documentation",
          difficulty: "beginner",
          estimatedTime: "Daily",
          url: "https://pib.gov.in/",
        },
      ],
    },
    {
      id: "upsc-phase-2",
      phase: 2,
      title: "Mains Syllabus Mastery & Analytical Answer Writing",
      description: "Develop deep subject comprehension across GS Papers I–IV, ethics case studies, and structured essay writing.",
      estimatedDuration: "6–8 weeks",
      skills: ["Structured Analytical & Answer Writing", "Public Policy & Grassroots Development"],
      learn: [
        "General Studies Papers I–IV syllabus mapping: History/Geography (GS1), Governance/Polity/IR (GS2), Economy/Environment/Security (GS3), Ethics/Integrity/Aptitude (GS4)",
        "Answer writing structure: concise introduction, structured arguments with sub-headings, flowchart utilization, and balanced forward-looking conclusion",
        "Administrative ethics case studies: navigating conflict of interest, political pressure, and resource scarcity",
        "Essay paper strategy: brainstorming multidimensional arguments across social, economic, political, and philosophical lenses",
      ],
      practice: [
        "Write 2 timed GS answers daily with self-evaluation against official UPSC marking benchmarks",
        "Draft a complete 1,000-word analytical essay on a contemporary governance or public policy topic",
      ],
      build: "A comprehensive Mains answer writing portfolio: 20 graded GS answers, 3 structured essays, and 10 solved ethical case studies.",
      resources: [
        {
          name: "PRS Legislative Research — Official Policy & Bill Analysis",
          type: "documentation",
          difficulty: "intermediate",
          estimatedTime: "Ongoing",
          url: "https://prsindia.org/",
        },
        {
          name: "Sansad TV Official Discussions & Debates",
          type: "video",
          difficulty: "intermediate",
          estimatedTime: "Weekly",
          url: "https://sansadtv.nic.in/",
        },
      ],
    },
    {
      id: "upsc-phase-3",
      phase: 3,
      title: "Optional Subject Depth, Previous Years Papers & Personality Prep",
      description: "Consolidate specialized knowledge, practice simulated test series, and build administrative personality attributes.",
      estimatedDuration: "Ongoing",
      skills: ["Crisis Management & Administrative Leadership", "Indian Polity & Constitutional Governance"],
      learn: [
        "Specialized subject selection and deep coverage for the two Optional papers (500 marks total)",
        "Rigorous analysis of 10 years of UPSC Prelims and Mains Previous Year Questions (PYQs)",
        "Interview board personality preparation: detailed application form (DAF) defense, state profile, and international affairs",
        "Stress management, mental stamina, and ethical conviction under rigorous competitive scrutiny",
      ],
      practice: [
        "Solve 15 full-length simulated UPSC Prelims mock tests with negative marking calculation",
        "Participate in structured mock interviews and group discussions on policy reform",
      ],
      build: "A complete civil service candidacy portfolio: detailed DAF profile, optional subject synopsis sheets, and performance metrics from mock tests.",
      resources: [
        {
          name: "UPSC Previous Years Question Papers (Official Archive)",
          type: "practice",
          difficulty: "advanced",
          estimatedTime: "Ongoing",
          url: "https://upsc.gov.in/examinations/previous-question-papers",
        },
      ],
    },
  ],
  projects: [
    {
      title: "District Governance Bottleneck Case Study",
      difficulty: "beginner",
      skills: ["Governance Analysis", "Policy Evaluation", "Problem Solving"],
      description: "Analyze a real district-level administrative bottleneck (such as primary health centre medicine availability or municipal waste management) and formulate a practical executive action plan.",
      features: [
        "Root cause breakdown examining administrative, financial, and logistical causes",
        "Stakeholder mapping: citizens, local panchayat, district administration, and field staff",
        "A 30-60-90 day phased implementation roadmap with measurable milestones",
      ],
      portfolioValue: "Demonstrates practical governance thinking and executive problem-solving capability.",
    },
    {
      title: "Comparative Public Scheme Impact Evaluation",
      difficulty: "intermediate",
      skills: ["Public Policy", "Data Analysis", "Grassroots Development"],
      description: "Perform an evidence-backed evaluation of a major government scheme (such as Jal Jeevan Mission or PM Awas Yojana), assessing target vs. actual delivery, fiscal efficiency, and citizen satisfaction.",
      features: [
        "Analysis of official government datasets and CAG / NITI Aayog evaluation reports",
        "Identification of leakages, inclusion/exclusion errors, and last-mile hurdles",
        "Concrete policy recommendations for technological monitoring and transparency",
      ],
      portfolioValue: "Proves capacity for rigorous public policy evaluation and evidence-based recommendations.",
    },
    {
      title: "Administrative Ethics & Crisis Resolution Memo",
      difficulty: "advanced",
      skills: ["Administrative Ethics", "Crisis Leadership", "Legal Reasoning"],
      description: "Draft an authoritative administrative memorandum resolving a simulated crisis: reconciling communal tensions during a festival while maintaining public order, constitutional secularism, and human dignity.",
      features: [
        "Statutory basis under CrPC/BNSS and Police Acts for executive decisions",
        "Balancing competing citizen rights and public security imperatives",
        "Communication protocol for media, civil society, and community elders",
      ],
      portfolioValue: "Shows ethical maturity, constitutional grounding, and crisis leadership temperament.",
    },
  ],
  progression: [
    {
      title: "Sub-Divisional Magistrate (SDM) / Assistant SP",
      yearsRange: "1–4 years post-academy training",
      responsibilities: [
        "Administer sub-divisional law and order, land revenue courts, and local regulatory licensing",
        "Supervise grassroots delivery of flagship government developmental schemes",
        "Direct local emergency disaster relief and citizen grievance redressal forums",
      ],
      skills: ["Field Administration", "Statutory Powers", "Crisis Management", "Citizen Interface"],
      deltaFromPrevious: "Entry-level cadre posting after Lal Bahadur Shastri National Academy of Administration (LBSNAA) training.",
    },
    {
      title: "District Magistrate & Collector (DM) / Superintendent of Police (SP)",
      yearsRange: "5–12 years",
      responsibilities: [
        "Head the entire district administrative and revenue machinery or district police force",
        "Coordinate inter-departmental operations: health, education, infrastructure, and agriculture",
        "Lead district disaster management authority during natural calamities and crises",
      ],
      skills: ["Executive Leadership", "Inter-Departmental Command", "Disaster Response", "Public Trust"],
      deltaFromPrevious: "Apex district responsibility with substantial statutory and executive command.",
    },
    {
      title: "Special Secretary / DIG of Police / Director in Central Ministry",
      yearsRange: "13–20 years",
      responsibilities: [
        "Draft statewide departmental policies and monitor multi-district program execution",
        "Formulate statutory rules, state budgets, and legislative bills for state assemblies",
        "Lead central deputation wings within ministries (Finance, Home, Commerce, Defense)",
      ],
      skills: ["Policy Formulation", "Legislative Drafting", "Public Finance", "Strategic Governance"],
      deltaFromPrevious: "Transition from district field management to state/national policy leadership.",
    },
    {
      title: "Principal Secretary / Additional Director General (ADG)",
      yearsRange: "20–28 years",
      responsibilities: [
        "Command apex state government departments (Home, Finance, Revenue, Education)",
        "Direct major infrastructure investments, state economic policies, and regulatory authorities",
        "Represent the state government in bilateral negotiations and inter-state councils",
      ],
      skills: ["Institutional Leadership", "High-Stakes Negotiations", "Macroeconomic Policy"],
      deltaFromPrevious: "Apex department-level authority directing statewide civil services.",
    },
    {
      title: "Chief Secretary of State / Union Cabinet Secretary",
      yearsRange: "30+ years",
      responsibilities: [
        "Serve as highest-ranking civil servant advising the Chief Minister or Prime Minister of India",
        "Chair the Committee of Secretaries and coordinate all civil and internal security policies",
        "Lead national administrative reforms, crisis coordination, and bureaucratic governance",
      ],
      skills: ["National Leadership", "Crisis Stewardship", "Cabinet Advisory", "Constitutional Stewardship"],
      deltaFromPrevious: "Apex bureaucratic position in India, shaping governance for the entire nation.",
    },
  ],
  preparation: [
    {
      id: "upsc-prep-1",
      category: "Eligibility",
      task: "Verify Official Eligibility & Timeline",
      details: "Ensure completion of recognized graduation degree (in any stream) and age eligibility (21–32 for General category, relaxations for OBC/SC/ST as per official notification).",
    },
    {
      id: "upsc-prep-2",
      category: "Foundations",
      task: "Complete Core NCERT Readings",
      details: "Read foundational NCERT textbooks for Classes 6–12 in History, Geography, Polity, and Economics to build clear conceptual terminology.",
    },
    {
      id: "upsc-prep-3",
      category: "Current Affairs",
      task: "Establish Daily Current Affairs Analysis",
      details: "Read one national newspaper daily and official PIB releases, categorizing developments under relevant General Studies syllabus headings.",
    },
    {
      id: "upsc-prep-4",
      category: "Exam Strategy",
      task: "Deconstruct UPSC Syllabus & PYQs",
      details: "Analyze the exact UPSC CSE syllabus and 5 years of Preliminary and Main question papers to understand question patterns before buying reference books.",
    },
    {
      id: "upsc-prep-5",
      category: "Suitability",
      task: "Reflect on Career Suitability vs. Exam Success",
      details: "Acknowledge the high selectivity of competitive exams. Build genuine interest in public service while maintaining parallel career pathways and graduate qualifications.",
    },
  ],
};
