import {
  Cpu,
  Brain,
  Lightbulb,
  Heart,
  FlaskConical,
  DollarSign,
  Rocket,
  Briefcase,
  Megaphone,
  Palette,
  Scale,
  Users,
  Shield,
  Cloud,
  Bot,
  Database,
  BarChart3,
  Gamepad2,
  Film,
  Truck,
  Activity,
  Dna,
  Radio,
  Layers,
  type LucideIcon,
} from "lucide-react";

export const CAREER_ICON_MAP: Record<string, LucideIcon> = {
  // Canonical 24 Career Paths
  "Software Development": Cpu,
  "Cloud & Infrastructure Systems": Cloud,
  "Cybersecurity & Defense": Shield,
  "Cybersecurity": Shield,
  "Robotics & Automation": Bot,
  "Robotics & Automation Systems": Bot,
  "IoT & Connected Systems": Radio,
  "IoT": Radio,
  "Core & Systems Engineering": Lightbulb,
  "Engineering": Lightbulb,

  "Artificial Intelligence & Data": Brain,
  "Data Engineering & Platforms": Database,
  "Data Engineering & Infrastructure": Database,
  "Business Intelligence & Analytics": BarChart3,
  "Data Analytics & Insights": BarChart3,

  "Digital Product & UI/UX Design": Layers,
  "UI/UX & Product Design": Layers,
  "Design & Creative Arts": Palette,
  "Visual Brand & Spatial Design": Palette,
  "Visual & Brand Communication": Palette,
  "Game & Interactive Media": Gamepad2,
  "Game & Interactive Media Design": Gamepad2,
  "Animation & 3D Media": Film,

  "Financial Markets & Quantitative Investment": DollarSign,
  "Finance & FinTech": DollarSign,
  "Finance / Investment Banking": DollarSign,
  "Strategic Management & Product Leadership": Briefcase,
  "Product & Operations Management": Briefcase,
  "Management / Product Management": Briefcase,
  "Venture Building & Entrepreneurship": Rocket,
  "Entrepreneurship & Ventures": Rocket,
  "Entrepreneurship": Rocket,
  "Supply Chain & Global Operations": Truck,

  "Clinical Medicine & Patient Care": Heart,
  "Medicine & Clinical Practice": Heart,
  "Medicine / Healthcare": Heart,
  "Scientific Research & Discovery": FlaskConical,
  "Scientific Research": FlaskConical,
  "Biotechnology & Pharmaceutical Sciences": Dna,
  "Biomedical & Pharmaceutical": Dna,
  "Biomedical Engineering": Dna,
  "Public Health & Global Epidemiology": Activity,

  "Strategic Marketing & Brand Communications": Megaphone,
  "Marketing & Digital Media": Megaphone,
  "Marketing / Media / Communications": Megaphone,
  "Legal Systems & Public Policy": Scale,
  "Law & Public Policy": Scale,
  "Law / Public Policy": Scale,
  "Psychological Sciences & Behavioral Health": Users,
  "Psychology & Behavioral Sciences": Users,
  "Psychology / Social Impact": Users,
  "Journalism & Media Broadcasting": Radio,
  "Journalism & Media Production": Radio,
  "Journalism": Radio,

  // Historical aliases
  "Software / App Development": Cpu,
  "AI / Machine Learning / Data Science": Brain,
};

export function getCareerIcon(careerName: string): LucideIcon {
  return CAREER_ICON_MAP[careerName] || Briefcase;
}
